
version: '3'
services:
  alpha7-mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_USER=sa
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=alpha7
    ports:
      - "3306:3306"
    networks:
      - spring-mysql-network
  alpha7-backend:
    networks:
      - spring-mysql-network
    image: alpha7
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://alpha7-mysql:3306/alpha7?createDatabaseIfNotExist=true&useSSL=false
      #      SPRING_DATASOURCE_URL: jdbc:mysql://alpha7-mysql:3306/demo?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "1234"
    build:
      context: "."
      dockerfile: "DockerFile"
    depends_on:
      - alpha7-mysql
networks:
  spring-mysql-network:

